### ISSUE TITLE
Fix potential typo in application.controller: new_session_url > new_user_session_url

### ISSUE THREAD

**Issue by iraszl** [gorails-screencasts/gorails-episode-80#1]
Related file: /app/controllers/application_controller.rb
Line #15: `elsif request.referer == new_session_url`
Suggested change: `elsif request.referer == new_user_session_url`

I think new_session_url is not a valid method. The application seems to work correctly with new_user_session_url instead.

**Comment by excid3** [comment]
I think you're right, want to send a PR?

**Comment by iraszl** [comment]
Done.

**Comment by excid3** [comment]
Thanks @iraszl. 🤘
